# Generated by Django 5.2.8 on 2025-11-29 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', through='jobs.SavedJob', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='jobs_job_categor_653d6e_idx'),
        ),
    ]
